baseURL = "https://ahmadchreiff.github.io/personal-website/"
languageCode = "en-us"
title = "Ahmad"
enableRobotsTXT = true

[params]
  accentColor = "#860033"
  name = "Ahmad"
  tagline = "CS & Applied Math Student"
